#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# scripts/setup-dev.sh
# Bootstrap the local development `.env` for stack.
#
# Writes the repo-root `.env` — the only env file every workspace and compose
# file reads — from `.env.example`, replacing its placeholder secrets with real
# ones generated by openssl (≥32 chars) and enabling the admin seed. An
# existing `.env` is preserved unless --force.
#
# Production deployments get their own `.env` from scripts/bootstrap.sh, run in
# the deployment directory, not in this checkout.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

force=0
for arg in "$@"; do
  case "$arg" in
    --force | -f) force=1 ;;
    -h | --help)
      echo "usage: $0 [--force]"
      echo "  --force, -f   overwrite an existing .env"
      exit 0
      ;;
    *)
      echo "unknown flag: $arg" >&2
      exit 2
      ;;
  esac
done

if ! command -v openssl >/dev/null 2>&1; then
  echo "error: openssl is required to generate secrets" >&2
  exit 1
fi

EXAMPLE="$REPO_ROOT/.env.example"
ENV_FILE="$REPO_ROOT/.env"

# Leftovers from the per-app layout: nothing reads them any more, so values
# kept only there are silently lost. Warn, never delete — they hold secrets.
stale=()
for file in "$REPO_ROOT"/apps/*/.env; do
  [[ -f "$file" ]] && stale+=("${file#"$REPO_ROOT/"}")
done
if ((${#stale[@]})); then
  echo "⚠ Found per-app env files that are no longer read:"
  printf "    %s\n" "${stale[@]}"
  echo "  Move any values you still need into .env, then delete them."
  echo ""
fi

existed=0
[[ -f "$ENV_FILE" ]] && existed=1
if ((existed && !force)); then
  echo "  ↳ .env already exists, skipping (use --force to overwrite)"
  exit 0
fi

BETTER_AUTH_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
# AES-256 master key for the certificate vault: exactly 32 bytes.
CERTIFICATE_ENCRYPTION_KEY="$(openssl rand -base64 32 | tr -d '\n')"
# Must be a valid address for zod's z.email() in packages/env: "admin@localhost"
# has no TLD and fails validation, which crashes the backend on boot.
ADMIN_EMAIL="admin@stack.local"
ADMIN_NAME="Admin"
ADMIN_PASSWORD="$(openssl rand -base64 24 | tr -d '\n')"

echo "→ Generating Better Auth, certificate vault and admin secrets with openssl..."

# Copy .env.example, setting each listed variable on its `KEY=` or `# KEY=`
# line. Values go through the environment so awk never interprets them.
# umask 077 so the file is created 600: it holds real secrets.
umask 077
BETTER_AUTH_SECRET="$BETTER_AUTH_SECRET" \
  CERTIFICATE_ENCRYPTION_KEY="$CERTIFICATE_ENCRYPTION_KEY" \
  ADMIN_EMAIL="$ADMIN_EMAIL" ADMIN_NAME="$ADMIN_NAME" \
  ADMIN_PASSWORD="$ADMIN_PASSWORD" \
  awk '
    BEGIN {
      split("BETTER_AUTH_SECRET CERTIFICATE_ENCRYPTION_KEY ADMIN_EMAIL ADMIN_NAME ADMIN_PASSWORD", keys, " ")
      for (i in keys) wanted[keys[i]] = 1
    }
    {
      line = $0
      sub(/^# /, "", line)
      key = line
      sub(/=.*/, "", key)
      if (line ~ /^[A-Z_]+=/ && (key in wanted)) {
        print key "=" ENVIRON[key]
        next
      }
      print
    }
  ' "$EXAMPLE" > "$ENV_FILE"
chmod 600 "$ENV_FILE"

if ((existed)); then
  echo "  ↻ .env overwritten"
else
  echo "  ✓ .env created"
fi

echo ""
echo "✓ Done. Next:"
echo "  # set DATABASE_URL in .env to your external dev PostgreSQL"
echo "  bun install"
echo "  bun run dev         # Docker dev stack, Loki included"
echo "  # or: bun run loki:start && bun run dev:local"
echo "  # the backend applies migrations and seeds the admin on boot"
echo ""
echo "  Admin credentials (created on first backend boot, idempotent):"
printf "    email:    %s\n" "$ADMIN_EMAIL"
printf "    password: %s\n" "$ADMIN_PASSWORD"
echo ""
echo "  ⚠ Save the password now — it is not stored anywhere else."
