/**
 * Generates the Lucide icon catalog used by the entity icon picker.
 *
 * `lucide-react` ships icon geometry but no categories or tags, so this script
 * pairs the installed package with Lucide's upstream metadata for the exact
 * same version. Run it after upgrading `lucide-react` (`bun run icons:catalog`)
 * and commit the generated files; builds never fetch anything.
 */

import { spawnSync } from "node:child_process"
import { mkdtemp, readdir, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { fileURLToPath } from "node:url"
import { dynamicIconImports } from "lucide-react/dynamic"

type IconNode = [string, Record<string, unknown>, IconNode[]?]

type IconMetadata = {
  tags?: string[]
  categories?: string[]
  aliases?: { name: string; deprecated?: boolean }[]
}

type CategoryMetadata = { title: string }

const FRONTEND_DIR = fileURLToPath(new URL("..", import.meta.url))
const OUTPUT_DIR = join(FRONTEND_DIR, "src/features/entity-icons/picker/model")

async function installedLucideVersion() {
  const manifest = JSON.parse(
    await readFile(
      join(FRONTEND_DIR, "node_modules/lucide-react/package.json"),
      "utf8"
    )
  ) as { version: string }
  return manifest.version
}

/** Downloads and unpacks the lucide repository at `version`; returns its root. */
async function downloadLucideSource(version: string, workDir: string) {
  const url = `https://codeload.github.com/lucide-icons/lucide/tar.gz/refs/tags/${version}`
  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(
      `Lucide metadata for ${version} not found (${response.status} ${url}). ` +
        "Refusing to mix metadata from another version."
    )
  }
  const archive = join(workDir, "lucide.tar.gz")
  await writeFile(archive, Buffer.from(await response.arrayBuffer()))

  const tar = spawnSync("tar", ["-xzf", archive, "-C", workDir], {
    encoding: "utf8",
  })
  if (tar.status !== 0) {
    throw new Error(`tar failed: ${tar.stderr}`)
  }
  return join(workDir, `lucide-${version}`)
}

async function readJsonDir<T>(dir: string) {
  const entries = new Map<string, T>()
  for (const file of (await readdir(dir)).sort()) {
    if (!file.endsWith(".json")) continue
    const id = file.slice(0, -".json".length)
    entries.set(id, JSON.parse(await readFile(join(dir, file), "utf8")) as T)
  }
  return entries
}

/** React keys are re-created at load time; dropping them shrinks the file. */
function stripKeys(nodes: IconNode[]): IconNode[] {
  return nodes.map(([tag, attrs, children]) => {
    const { key: _key, ...rest } = attrs
    return children ? [tag, rest, stripKeys(children)] : [tag, rest]
  })
}

async function main() {
  const version = await installedLucideVersion()
  const workDir = await mkdtemp(join(tmpdir(), "lucide-catalog-"))

  try {
    console.log(`Fetching Lucide ${version} metadata…`)
    const sourceDir = await downloadLucideSource(version, workDir)
    const iconMetadata = await readJsonDir<IconMetadata>(
      join(sourceDir, "icons")
    )
    const categoryMetadata = await readJsonDir<CategoryMetadata>(
      join(sourceDir, "categories")
    )
    for (const [id, category] of categoryMetadata) {
      if (typeof category.title !== "string") {
        throw new Error(`Category ${id} has no title; metadata layout changed`)
      }
    }

    const icons = []
    for (const name of Object.keys(dynamicIconImports).sort()) {
      const module = (await dynamicIconImports[
        name as keyof typeof dynamicIconImports
      ]()) as { __iconData?: { name?: string; node: IconNode[] } }
      const data = module.__iconData
      // Alias modules re-export the canonical icon; list each icon once.
      if (!data || (data.name && data.name !== name)) continue

      const metadata = iconMetadata.get(name)
      const aliases = (metadata?.aliases ?? [])
        .filter((alias) => !alias.deprecated)
        .map((alias) => alias.name)
      icons.push({
        name,
        categories: (metadata?.categories ?? []).filter((id) =>
          categoryMetadata.has(id)
        ),
        tags: [...new Set([...(metadata?.tags ?? []), ...aliases])],
        node: stripKeys(data.node),
      })
    }

    const usedCategories = new Set(icons.flatMap((icon) => icon.categories))
    const categories = [...categoryMetadata]
      .filter(([id]) => usedCategories.has(id))
      .map(([id, category]) => ({ id, title: category.title }))

    await writeFile(
      join(OUTPUT_DIR, "icon-catalog.generated.json"),
      `${JSON.stringify({ version, categories, icons })}\n`
    )

    const ids = categories.map((category) => `  "${category.id}",`).join("\n")
    await writeFile(
      join(OUTPUT_DIR, "icon-categories.generated.ts"),
      `// Generated by apps/frontend/scripts/generate-icon-catalog.ts — do not edit.
// Lucide ${version}.

export const iconCategoryIds = [
${ids}
] as const

export type IconCategoryId = (typeof iconCategoryIds)[number]
`
    )

    console.log(
      `Wrote ${icons.length} icons in ${categories.length} categories (Lucide ${version}).`
    )
  } finally {
    await rm(workDir, { recursive: true, force: true })
  }
}

await main()
