export const documentLabels = {
  upload: "Subir PDF",
  uploadSubmit: "Subir",
  uploadDescription:
    "El PDF se guarda cifrado. Debe ocupar como máximo 20 MB y no estar protegido con contraseña.",
  file: "Archivo PDF",
  filePrompt: "Arrastra el PDF aquí o haz clic para elegirlo",
  fileRequirements: "PDF · hasta 20 MB · sin contraseña",
  fileRequired: "Elige un archivo PDF",
  fileTooLarge: "El PDF ocupa más de 20 MB",
  fileNotPdf: "Ese archivo no es un PDF",
  dropTitle: "Suelta un PDF para firmarlo",
  dropActive: "Suéltalo para subirlo",
  dropDescription:
    "Hasta 20 MB y sin contraseña. Se guarda cifrado y se abre listo para firmar.",
  dropChoose: "Elegir PDF",
  dropUploading: (name: string) => `Subiendo «${name}»…`,
  library: "Ver todos los documentos",
  open: "Abrir",
  download: "Descargar",
  delete: "Eliminar",
  deleteTitle: "Eliminar documento",
  deleteDescription: (name: string) =>
    `Se eliminará "${name}" con todas sus versiones de forma permanente. El registro de sus firmas se conserva.`,
  pages: "Páginas",
  size: "Tamaño",
  signatures: "Firmas",
  lastSigned: "Última firma",
  unsigned: "Sin firmar",
  signed: "Firmado",
} as const
